function p = dipoleMoment(psi1,psi2,dim)
% dipoleMoment The dipole moment between two 3d wave-functions
%   p = dipoleMoment(psi1,psi2,dim) calculates the dipole moment between two 
%   wavefunctions, psi1 and psi2. 
%
%   The function returns the dipole moment as a 3 element column vector. In 
%   Bra-Ket notation, this operation is expressed as p = <psi1|r|psi2>.
%
%   - psi1 and psi2 are NxNxN arrays, typically generated by 
%     evaluateHydrogenicWavefunction().
%
%   - dim is an array mapping the (i,j,k) element of each wavefunction to a 
%     point in space [dim(i), dim(j), dim(k)]

% Copyright 2009 The MathWorks, Inc.

% Preallocate the array to store the calculated dipole moment in.
p = zeros(3,1);

% Calculate 3 arrays to lookup [x,y,z] from [i,j,k]. 
% At point i,j,k, x = rx(i,j,k) etc.
[ry rx rz] = meshgrid(yDim,dim,zDim);


% For each of x,y,z, calculate p_x = sum( conjugate(psi1)*x*psi2 ) etc. 
% for all elements of psi1,psi2.
psi1_2 = conj(psi1).*psi2;
p(1) = sum(sum(sum( rx .* psi1_2 )));
p(2) = sum(sum(sum( ry .* psi1_2 )));
p(3) = sum(sum(sum( rz .* psi1_2 )));


% Assuming regular grid. I.e. assuming that dim(i+1)-dim(i) is the same for 
% all i.
dx = dim(2)-dim(1);


% Get an approximation of the dipole moment by multiplying the discrete 
% sum by the volume element.
p = p * dx^3;
