function psiList = getPsiList( varargin )
% getPsiList Finds, loads or generates the list of wavefunctions
%   genPsiList loads a wavefunction list from disk. It caches the list in
%   persistent memory, so that if getPsiList() is called multiple times for the
%   same list, only the first call will involve loading it from disk.
%
%   Syntax :
%
%     psiList = getPsiList()
%       Look for a '.mat' file on the MATLAB path called 'psiList', containing
%       a structure 'psiList', and loads it. If such a file does not exist, a
%       psiList is generated by using generateWavefunctionList()'s default
%       options. 
%
%     psiList = getPsiList( listName )
%       Look for a '.mat' file on the MATLAB path with name 'listName',
%       containing  a structure 'psiList', and loads it. If such a file does not
%       exist, an error is raised.

% Copyright 2009 The MathWorks, Inc.

persistent loadedPsiList loadedListName


if ~any( nargin == [0 1] )
    error('Wavefunction:invalidArgument', 'Incorrect number of arguments');
end

if nargin == 0
    % By default, we will look for a listName of 'psiList'.
    listName = 'psiList';
    
    userProvidedListName = false;
elseif ~ischar(varargin{1})
    error('Wavefunction:invalidArgument', 'listName must be a single string');
else
    % We will use the user provided listName
    listName = varargin{1};
    
    userProvidedListName = true;
end


% Have we got the correct list loaded into persistent storage?
if strcmp( loadedListName, listName)
    % If so, life is easy; just return the stored psiList.
    psiList = loadedPsiList;
    return;
end


% Search for the list on the path
if exist([listName '.mat'],'file')
    fprintf('Loading %s ...\n',listName);
    
    s = load(listName);
    
    if isfield( s, 'psiList')
        psiList = s.psiList;
    else
        error('Wavefunction:invalidFormat', ...
                ['Loaded .mat file ''%s'' does not contain a wavefunction ', ...
                 'list named ''psiList'''], listName);
    end
    
elseif ~userProvidedListName
    % If the the user did not provide the listName we generate psiList.
    psiList = generateWavefunctionList();
    
    % And save it to the CWD
    save('psiList','psiList');
else
    % If the callee provided 'listName', and we could not find it, error
    % out.
    error('Wavefunction:fileNotFound', ...
            'Could not find wavefunction list ''%s.mat''', listName);
end


% Save the psiList and the file name it was loaded from to our persistent
% storage, in case we need to use it at a later date.
loadedPsiList = psiList;
loadedListName = listName;
